### ISSUE TITLE
Release on conda

### ISSUE THREAD

**Issue by jtpio** [QuantStack/jupyterlab-snippets#13]
It would be great to have this package released on conda as well!

**Comment by mariobuikhuizen** [comment]
That's in progress:
https://github.com/conda-forge/staged-recipes/pull/11182

**Comment by jtpio** [comment]
Perfect, thanks!

**Comment by jtpio** [comment]
Closing as fixed.

Feedstock available at: https://github.com/conda-forge/jupyterlab-snippets-feedstock
