### ISSUE TITLE
Conflicting Dependencies with jupyterlab 2.1.4

### ISSUE THREAD

**Issue by JoopBanaan** [QuantStack/jupyterlab-snippets#22]
The command <jupyter labextension install @quentinandre/jupyterlab_snippets>                            
results in the following error message:
Conflicting Dependencies:                                        
JupyterLab              Extension      Package                   
>=2.1.2 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/application  
>=2.1.1 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/apputils     
>=4.1.0 <4.2.0          >=2.1.3 <3.0.0 @jupyterlab/coreutils     
>=2.1.2 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/notebook

**Comment by jtpio** [comment]
> The command <jupyter labextension install @quentinandre/jupyterlab_snippets>

This looks like the wrong extension.

What happens when installing from pip (https://github.com/QuantStack/jupyterlab-snippets#install) and then executing `jupyter lab build`?

**Comment by JoopBanaan** [comment]
Indeed that helps, my mistake
